-- Quake Player Rankings — community submissions table + policies (feature 5).
-- Run once in the Supabase SQL editor (Dashboard -> SQL Editor -> paste -> Run).
-- Idempotent: safe to re-run (table create is one-shot; grants and policies are
-- restated/recreated every run).
--
-- Model: the public (anon) can ONLY INSERT pending submissions — no reads, no
-- edits; submissions are invisible until the admin reviews them in /admin.
-- The admin uid (must match scripts/setup-admin.sql — create-admin-user.js
-- emits it) gets SELECT/UPDATE/DELETE.
--
-- Spam posture (review-before-apply is the real gate):
--   * honeypot: the `website` column is a hidden trap field — WITH CHECK
--     rejects any insert that fills it, so bot rows are never stored.
--   * length caps as DB constraints — client maxLength is UX, this is the
--     enforcement (the INSERT endpoint is open to anon by design).
--   * column-level INSERT grant: Supabase default privileges grant table-wide
--     ALL to anon on new tables, so we revoke-then-narrow — anon cannot supply
--     id / created_at / status (status = column default + WITH CHECK).

create table if not exists public."Submissions" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null,
  target_id bigint,            -- Tournaments row id (corrections only; no FK —
                               -- Tournaments.id has no unique constraint)
  payload jsonb not null,      -- the full proposed row, Tournaments column shape
  note text,                   -- optional submitter note for the reviewer
  handle text,                 -- optional submitter name/handle
  status text not null default 'pending',
  website text not null default '',  -- honeypot: humans never see the field
  constraint submissions_type_check check (type in ('new', 'correction')),
  constraint submissions_status_check check (status in ('pending', 'approved', 'rejected')),
  constraint submissions_correction_target check (type <> 'correction' or target_id is not null),
  constraint submissions_note_cap check (char_length(coalesce(note, '')) <= 500),
  constraint submissions_handle_cap check (char_length(coalesce(handle, '')) <= 40),
  constraint submissions_payload_cap check (length(payload::text) <= 4000)
);

alter table public."Submissions" enable row level security;

revoke all on public."Submissions" from anon;
revoke all on public."Submissions" from authenticated;
grant insert (type, target_id, payload, note, handle, website)
  on public."Submissions" to anon;
grant select, update, delete on public."Submissions" to authenticated;

-- The identity sequence: anon inserts need nextval. Resolved dynamically so
-- the generated sequence name never has to be spelled out.
do $$
begin
  execute format(
    'grant usage on sequence %s to anon',
    pg_get_serial_sequence('public."Submissions"', 'id')
  );
end $$;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'Submissions'
  loop
    execute format('drop policy %I on public."Submissions"', pol.policyname);
  end loop;
end $$;

create policy "anon submit pending" on public."Submissions"
  for insert to anon
  with check (status = 'pending' and coalesce(website, '') = '');

create policy "admin read" on public."Submissions"
  for select to authenticated using (auth.uid() = 'bcbf6194-e890-489c-b0a0-1f329507651e');

create policy "admin update" on public."Submissions"
  for update to authenticated
  using (auth.uid() = 'bcbf6194-e890-489c-b0a0-1f329507651e') with check (auth.uid() = 'bcbf6194-e890-489c-b0a0-1f329507651e');

create policy "admin delete" on public."Submissions"
  for delete to authenticated using (auth.uid() = 'bcbf6194-e890-489c-b0a0-1f329507651e');
